### Question 1
    Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
x=np.array([1,42,546,76,8])
y=np.array([12,42,554,2,22])

In [2]:
# Greater
print(np.greater(x,y))

[False False False  True False]


In [3]:
# Greater_equal
print(np.greater_equal(x,y))

[False  True False  True False]


In [4]:
# less
print(np.less(x,y))

[ True False  True False  True]


In [5]:
#Less_equal
print(np.less_equal(x,y))

[ True  True  True False  True]


### Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [6]:
zero=np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
five=np.ones(10)*5
print(five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [9]:
array=np.random.randn(4,5)*20
print(array)

[[ -5.63409071   3.65486964  14.07874083  46.79547447   8.90280636]
 [-12.85440005  -4.80462722  38.56997623   7.83066988  -5.3034711 ]
 [ -4.7405688   -4.73850244 -20.64748155  -3.14313574  29.02295406]
 [ 10.87768521 -17.90999552  11.82117366 -32.08463005 -16.8845682 ]]


In [10]:
# sumof all the elements
print(array.sum())

42.80887896312801


In [11]:
# sum of each row
print(array.sum(axis=1))

[ 67.79780058  23.43814774  -4.24673446 -44.1803349 ]


In [12]:
# sum of each column
print(array.sum(axis=0))

[-12.35137435 -23.79825553  43.82240917  19.39837856  15.73772111]


### Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [13]:
arr1=np.arange(1,6)
arr2=np.arange(4,9)
print(arr1,arr2,sep='\n')

[1 2 3 4 5]
[4 5 6 7 8]


In [14]:
#Addition
a,s,m,d=[],[],[],[]
for i in range(len(arr1)):
    a.append(np.add(arr1[i],arr2[i]))
    s.append(np.subtract(arr1[i],arr2[i]))
    m.append(np.multiply(arr1[i],arr2[i]))
    d.append(np.divide(arr1[i],arr2[i]))
print("ADDITION",a)
print("SUBTRACTION",s)
print("MULTIPLICATION",m)
print("DIVISION",d)

ADDITION [5, 7, 9, 11, 13]
SUBTRACTION [-3, -3, -3, -3, -3]
MULTIPLICATION [4, 10, 18, 28, 40]
DIVISION [0.25, 0.4, 0.5, 0.5714285714285714, 0.625]


### Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree

In [15]:
degree=np.array([0,30,45,60,90],dtype=float)
degree

array([ 0., 30., 45., 60., 90.])

In [16]:
#sine
sine=np.sin(degree*np.pi/180)
print(sine)

[0.         0.5        0.70710678 0.8660254  1.        ]


In [17]:
#cosine
cosine=np.cos(degree*np.pi/180)
print(cosine)


[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [18]:
#tangent
tangent=np.tan(degree*np.pi/180)
print(tangent)

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [19]:
import pandas as pd
student={'Name':['Bucky','Faltus','Amigo','Mickey Mouse'],'Age':[20,21,21,20],'Gender':['M','M','M','M']}
labels=['A',"B",'C','B']
df=pd.DataFrame(student,index=labels)
df

Name  Age Gender
A         Bucky   20      M
B        Faltus   21      M
C         Amigo   21      M
B  Mickey Mouse   20      M

### Question 7:
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.


In [20]:
student={'Name':['Bucky','Faltus','Amigo','Mickey Mouse'],'Age':[20,21,21,20],'Gender':['M','M','M','M'],'Score':[80,90,75,75]}
labels=['A',"B",'C','B']
df=pd.DataFrame(student,index=labels)
df[['Name','Score']]


Name  Score
A         Bucky     80
B        Faltus     90
C         Amigo     75
B  Mickey Mouse     75

### Question 8:
Write a Pandas program to join the two given dataframes along rows and assign all data

In [21]:
student_details1={'Name':['Bucky','Faltus','Amigo','Mickey Mouse'],'Age':[20,21,21,20],'Gender':['M','M','M','M'],'Score':[80,90,75,75]}
student_details2={'Name':['Morgan','MOnark','Vamic','Monic'],'Age':[20,21,21,20],'Gender':['F','F','F','F'],'Score':[85,90,70,75]}
labels=['A',"B",'C','B']
df1=pd.DataFrame(student_details1,index=labels)
df2=pd.DataFrame(student_details2,index=labels)

In [22]:
df1

Name  Age Gender  Score
A         Bucky   20      M     80
B        Faltus   21      M     90
C         Amigo   21      M     75
B  Mickey Mouse   20      M     75

In [23]:
df2

Name  Age Gender  Score
A  Morgan   20      F     85
B  MOnark   21      F     90
C   Vamic   21      F     70
B   Monic   20      F     75

In [24]:
df=pd.concat([df1,df2],axis=1)
df

Name  Age Gender  Score    Name  Age Gender  Score
A         Bucky   20      M     80  Morgan   20      F     85
B        Faltus   21      M     90  MOnark   21      F     90
C         Amigo   21      M     75   Vamic   21      F     70
B  Mickey Mouse   20      M     75   Monic   20      F     75

### Question 9:
Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [25]:
student={'Name':['Bucky','Faltus','Amigo','Mickey Mouse'],'Age':[20,21,np.nan,20],'Gender':['M','M','M','M'],'Score':[80,np.nan,75,75]}
labels=['A',"B",'C','B']
df=pd.DataFrame(student,index=labels)

In [26]:
df.isnull()

Name    Age  Gender  Score
A  False  False   False  False
B  False  False   False   True
C  False   True   False  False
B  False  False   False  False

### Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [27]:
df=pd.Series(np.arange(0,30,5))
df

0     0
1     5
2    10
3    15
4    20
5    25
dtype: int32